### ISSUE TITLE
Is it possible to get coloured outputs of Terragrunt plans?

### ISSUE THREAD

**Issue by kitos9112** [transcend-io/terragrunt-atlantis-config#111]
Hello!

Not 100% this is the right forum, but we leverage GitLab CICD flows and I wanted to present the changes to the infrastructure in a more concise and colored manner to my devs.

I noticed that many custom flows, including the official in the `atlantis` docs, point out to use the `no-color- flag of Terragrunt. Do you know if there's any workaround to add this coloured output as part of an Atlantis execution?

Cheers!

**Comment by dmattia** [comment]
Hello! I do not believe it is possible due to limitations on the GitLab CICD side of things, but if there is, creating an Issue over at https://github.com/runatlantis/atlantis is your best bet.

Closing as I think this is unrelated to this issue in particular, though an Issue in the atlantis repo makes sese
