### ISSUE TITLE
Verbose output on generate failure?

### ISSUE THREAD

**Issue by jmctune** [transcend-io/terragrunt-atlantis-config#203]
Hi there,

Cool project. We're using this not for atlantis support, but to generate the dependencies that a module or terragrunt file might have and parsing the yaml output against which files changed in our own custom pipelines. It's working well so far!

One thing we've recently run into is if a terraform file has a syntax error, the hcl parser won't be able to read the file and `terragrunt-atlantis-config` errors out (as expected). Here's an example of looking at 50+ projects and one file missing a closing bracket:

```
Error: Argument or block definition required: An argument or block definition is required here.
```

`terraform validate` would show:

```
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Argument or block definition required

  on main.tf line 47, in resource "aws_ssm_association" "configure":

An argument or block definition is required here.
```

There's no other output or help on which file is the problem, which is the ask of this request. Thank you!

**Comment by dmattia** [comment]
Hey @jmctune, thanks for the question!

I'm not sure that I have the bandwidth in the near future to add better error messages like `terraform validate` does, as I'm not quite sure where to start, but I would be interested in helping in another way if I can. If you are using golang, you should be able to call any of the helper methods we use directly, as I've tried to make many of them public.

If there are ever any private methods in this repo that you wish were public, please feel free to add an issue and I can change that for you quickly so that you can use this as a sort of SDK to find the dependencies 😃
