### ISSUE TITLE
Option --ignore-parent-terragrunt does not seem to work

### ISSUE THREAD

**Issue by gmaghera** [transcend-io/terragrunt-atlantis-config#35]
When I run generate I get an error on an include within the parent terragrunt.hcl file.  The structure of my project is very close to https://github.com/gruntwork-io/terragrunt-infrastructure-live-example, the model Terragrunt itself recommends.

The top-level terragrunt.hcl file contains lines like these:
```
account_vars     = read_terragrunt_config(find_in_parent_folders("account.hcl"))
region_vars      = read_terragrunt_config(find_in_parent_folders("region.hcl"))
environment_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))
backend_vars     = read_terragrunt_config(find_in_parent_folders("backend.hcl"))
```

The files referenced there, like account.hcl or region.hcl, are in lower-level directories than the top-level terragrunt.hcl.  However, the top-level terragrunt.hcl is never used directly.  It is included by lower-level terragrunt.hcl files, relative to which account.hcl or region.hcl are in a parent directory.

Here's the structure (omitting some directories for clarity):
```
.
├── backend.hcl
├── production
│   ├── account.hcl
│   ├── env.hcl
│   └── us-east-2
│       ├── ecr
│       │   ├── ecr.tf
│       │   └── terragrunt.hcl
│       ├── eks
│       │   └── terragrunt.hcl
│       ├── region.hcl
│       ├── route53
│       │   └── terragrunt.hcl
│       └── vpc
│           ├── terragrunt.hcl
│           └── vpc.tf
├── staging
│   ├── account.hcl
│   ├── env.hcl
│   └── us-east-2
│       ├── ecr
│       │   ├── ecr.tf
│       │   └── terragrunt.hcl
│       ├── eks
│       │   └── terragrunt.hcl
│       ├── keys
│       │   └── terragrunt.hcl
│       ├── region.hcl
│       ├── route53
│       │   └── terragrunt.hcl
│       └── vpc
│           └── terragrunt.hcl
└── terragrunt.hcl
```

And the error I get:
```
❯ terragrunt-atlantis-config generate --ignore-parent-terragrunt
Error: Error in function call

  on /Users/gmaghera/Workspaces/dc-terraform/terragrunt.hcl line 6, in locals:
   6:   backend_vars     = read_terragrunt_config(find_in_parent_folders("backend.hcl"))

Call to function "find_in_parent_folders" failed: ParentFileNotFound: Could not find a backend.hcl in any of the parent folders of
/Users/gmaghera/Workspaces/dc-terraform/terragrunt.hcl. Cause: Traversed all the way to the root..

[terragrunt] 2020/07/07 13:34:50 Encountered error while evaluating locals.
Error: /Users/gmaghera/Workspaces/dc-terraform/terragrunt.hcl:6,45-68: Error in function call; Call to function "find_in_parent_folders" failed: ParentFileNotFound: Could not find a backend.hcl in any of the parent folders of /Users/gmaghera/Workspaces/dc-terraform/terragrunt.hcl. Cause: Traversed all the way to the root..
Usage:
  terragrunt-atlantis-config generate [flags]

Flags:
      --autoplan                   Enable auto plan. Default is disabled
  -h, --help                       help for generate
      --ignore-parent-terragrunt   Ignore parent terragrunt configs (those which don't reference a terraform module). Default is disabled
      --output string              Path of the file where configuration will be generated. Default is not to write to file
      --root string                Path to the root directory of the github repo you want to build config for. Default is current dir (default "/Users/gmaghera/Workspaces/dc-terraform")
      --workflow string            Name of the workflow to be customized in the atlantis server. Default is to not set

/Users/gmaghera/Workspaces/dc-terraform/terragrunt.hcl:6,45-68: Error in function call; Call to function "find_in_parent_folders" failed: ParentFileNotFound: Could not find a backend.hcl in any of the parent folders of /Users/gmaghera/Workspaces/dc-terraform/terragrunt.hcl. Cause: Traversed all the way to the root..
```

**Comment by dmattia** [comment]
This is certainly an interesting bug! Thanks, @gmaghera for finding this

## Why this bug happens

We currently follow this pseudocode:

```pseudocode
files := find_all_terragrunt_files()
for file in files:
  parsed := parseFile(file)
  if the parsed file does not have a Terragrunt.Source value and --ignore-parent-terragrunt is on:
    skip this file
  else to all the dependency analysis stuff
```

The real life code is here: https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/cmd/generate.go#L103-L112

The `parseFile` in that pseudocode is actually using Terragrunt's parser, imported directly from their repo.

The error you are showing comes directly from the Terragrunt parser

## Why it's hard to fix this bug

If we don't use the parser, we cannot easily tell if a file is a parent terragrunt file or not. And then we don't know to skip that top level `terragrunt.hcl` file.

If we do use the Terragrunt parser, we get an error. This isn't so bad, except the error message is useless in this context. Terragrunt always parses `locals` first, so even if we could detect exactly the error in your output, we still wouldn't know if the file was a parent file or not.

## Workaround

As this fix may take a bit of time to create, here is a workaround: You could change the name of the top level `terragrunt.hcl` file to anything else, such as `parent.hcl`, and then update your child `path = find_in_parent_folders()` expressions to be `path = find_in_parent_folders("parent.hcl")`

This works because this repo uses the `FindConfigFilesInPath` directly from Terragrunt to determine which files are terraform modules: https://github.com/gruntwork-io/terragrunt/blob/24d9a82dd5c45aa0a08d56bafb95b3ffe8eb5a30/config/config.go#L237 and that function only looks for files named `terragrunt.hcl` or `terragrunt.hcl.json`: https://github.com/gruntwork-io/terragrunt/blob/24d9a82dd5c45aa0a08d56bafb95b3ffe8eb5a30/config/config.go#L22

At my company, we do this workaround, but not because we knew of the bug, but just because we have a few differently named parent config files we switch between based on infra environment.

## Actual fix

I think the only good fix here is to determine if a terragrunt file is a parent, while not parsing it with Terragrunt's parser, which means we'll need to parse the HCL on our own. I haven't done this before, but it doesn't look too awful.

**Comment by gmaghera** [comment]
Thank you David for the thoughtful analysis and the suggested workaround.  They both make sense.

**Comment by dmattia** [comment]
Upgrading to v0.5.0 should fix you issue, as I added in the HCL parsing. Please let me know if that fix didn't solve your problem :)

**Comment by gmaghera** [comment]
Thank you @dmattia.  Pardon the late reply, but I am still seeing an issue.

```
~/Workspaces/dc-terraform feature/DC-1036
(⎈ |dev:gql-review-liveness-a-qbs6k8)❯ terragrunt-atlantis-config version
terragrunt-atlantis-config '0.5.0'

~/Workspaces/dc-terraform feature/DC-1036
(⎈ |dev:gql-review-liveness-a-qbs6k8)❯ terragrunt-atlantis-config generate
Error: Error in function call

  on /Users/gmaghera/Workspaces/dc-terraform/terragrunt.hcl line 3, in locals:
   3:   account_vars     = read_terragrunt_config(find_in_parent_folders("account.hcl"))

Call to function "find_in_parent_folders" failed: ParentFileNotFound: Could not find a account.hcl in any of the parent folders of /Users/gmaghera/Workspaces/dc-terraform/terragrunt.hcl. Cause: Traversed all the way to the
root..

[terragrunt] 2020/07/20 10:23:46 Encountered error while evaluating locals.
Error: /Users/gmaghera/Workspaces/dc-terraform/terragrunt.hcl:3,45-68: Error in function call; Call to function "find_in_parent_folders" failed: ParentFileNotFound: Could not find a account.hcl in any of the parent folders of /Users/gmaghera/Workspaces/dc-terraform/terragrunt.hcl. Cause: Traversed all the way to the root..
Usage:
  terragrunt-atlantis-config generate [flags]

Flags:
      --autoplan                   Enable auto plan. Default is disabled
  -h, --help                       help for generate
      --ignore-parent-terragrunt   Ignore parent terragrunt configs (those which don't reference a terraform module). Default is disabled
      --output string              Path of the file where configuration will be generated. Default is not to write to file
      --parallel                   Enables plans and applys to happen in parallel. Default is enabled (default true)
      --root string                Path to the root directory of the github repo you want to build config for. Default is current dir (default "/Users/gmaghera/Workspaces/dc-terraform")
      --workflow string            Name of the workflow to be customized in the atlantis server. Default is to not set

/Users/gmaghera/Workspaces/dc-terraform/terragrunt.hcl:3,45-68: Error in function call; Call to function "find_in_parent_folders" failed: ParentFileNotFound: Could not find a account.hcl in any of the parent folders of /Users/gmaghera/Workspaces/dc-terraform/terragrunt.hcl. Cause: Traversed all the way to the root..
```

I am going to try the `parent.hcl` workaround, which seems quite acceptable to me, but I hope you find the report on using a parent `terragrunt.hcl` useful.
