### ISSUE TITLE
Default workspace locked error with generated config

### ISSUE THREAD

**Issue by justin-watkinson-sp** [transcend-io/terragrunt-atlantis-config#41]
I'm having some trouble getting some terragrunt-specific info about this issue and hoping there's some good input here.  I set up atlantis with a repo.yaml on the server so I can use this project to auto-generate the atlantis.yaml file in my repo for me.  I've tried editing one module (part of the same monorepo as the terragrunt.hcl files), or even just adjusting the terragrunt.hcl (non-parent) of an individual deployment.  I keep encountering this comment:

> the default workspace is currently locked by another command that is running for this pull request–wait until the previous command is complete and try again

Is there something in the atlantis.yaml I'm missing?  Trying to keep it simple.  I mean I could ignore that error, just not the greatest user experience.  I've already checked and doesn't seem like I'm getting double webhooks or anything like that.

**Comment by dmattia** [comment]
It sounds like you're off to a great start with that setup! This comment in particular (about the default workspace being locked) comes from Atlantis itself, but isn't really an error.

Here's how that comment can come up:
1. You open a pull request with some infra changes
2. If you have autoplan enabled, or comment `atlantis plan`, a plan will start
3. You update a file and push up a new commit
4. Atlantis will comment the warning you're seeing, letting you know that a plan has already started
5. The plan from step (2) above completes, commenting a plan out to your Pull Request.

This is just something that happens with Atlantis, and there aren't any changes to your atlantis.yaml you can make that will make this warning go away (in theory turning off autoplan could help with it, but that has its own considerations).

So, why does Atlantis have this issue when other CI/CD systems don't? Well, Atlantis is a single deployed instance that can only do a few things at a time. Lots of other CI/CD systems, like Github actions or CircleCi will dynamically bring up new docker images or virtual machines for you when you push up code, so even if you push a new commit every ten seconds, each push will generate its own new infra to run your tests on. But with Atlantis, the infra is constant, no matter how often you are pushing up commits. So that means there are cases where it might be asked to run a plan for `moduleX` when it's already running a plan for `moduleX` from an earlier commit, and it will have no good choice other than to reply with a comment like this.

**Comment by dmattia** [comment]
I'll close this for now, but feel free to comment if there's anything else related to this I can help with :)
