### ISSUE TITLE
Feature Request: ignore "sops_decrypt_file" function

### ISSUE THREAD

**Issue by tsunamishaun** [transcend-io/terragrunt-atlantis-config#77]
I have a multi account setup, running the tool from the root of my repo. When my creds line up with acccountA and there are calls/references to `sops_decrypt_file` it works but when it starts processing `AccountB/` my credentials are still pointed to `accountA`. If the function were ignored I could generate configs from the root without the terragrunt library trying to get the kms key from aws. Is there any way to ignore specific functions?

`terragrunt-atlantis-config generate --autoplan --parallel --create-project-name --ignore-parent-terragrunt --create-workspace --output ./atlantis.yaml`

```bash
.
├── accountA/
├── accountB/
├── atlantis.yaml
└── terragrunt.hcl
```

```bash
$> cat accountA/somedir/terragrunt.hcl
locals {
  secrets = jsondecode(sops_decrypt_file(find_in_parent_folders("blar.json")))
}
```

Error:
```bash
[terragrunt] Encountered error while evaluating locals.
Error: /accountB/somedir/terragrunt.hcl:5,38-56: Error in function call; Call to function "sops_decrypt_file" failed: Error getting data key: 0 successful groups required, got 0.
```

**Comment by dmattia** [comment]
Thanks for filing this issue!

What version of terragrunt-atlantis-config are you using? I can try to recreate this setup

We don't offer any way to ignore specific functions right now, but one option that stands out to me initially is that you could use:

```hcl
locals {
  secrets = try(
    jsondecode(sops_decrypt_file(find_in_parent_folders("blar.json"))),
    {}
  )
}
```

**Comment by tsunamishaun** [comment]
Running 0.9.7

@dmattia that though did cross my mind. New instance would need to be wrapped, new ones not wrapped would have a chance of breaking (small price to pay to get this working for now).

I was looking closely at the [wrapped Error](https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/cmd/generate.go#L191) and noticed it has the function name available to it `sops_decrypt_file`.  I admit filtering errors out by function name doesn't seem ideal. Thoughts?

A bit tangential but maybe you have some insight. I dont see many who use terragrunt and atlantis together using a single repo with multiple accounts off the root. I myself have setup runners per account and intercept the webhooks based on which files were changed. Sometimes I think just setting up a pipeline outside of atlantis would be better than having to monkey patch but I haven't given in quite yet.

**Comment by dmattia** [comment]
yeah I'm leaning against filtering out any Terragrunt errors. There will likely be cases where someone does care about errors coming from `sops_decrypt_file`

As for the multiple runners thoughts, it's an interesting question for sure. I know of at least a few (my own company included) places that have a single Atlantis that runs across multiple accounts, and it seems to work out well. I guess my primary focus is supporting the "one atlantis setup per repo" focus, because that's what Atlantis itself supports well: https://github.com/runatlantis/atlantis/issues/653

But I'd love to try and support your use case if I can. If you could create a simplified example showing the behavior that is giving you errors and open a PR placing it in this folder: https://github.com/transcend-io/terragrunt-atlantis-config/tree/master/test_examples

I will gladly write a test for that configuration and then update the code to make the test pass

**Comment by tsunamishaun** [comment]
Sorry for the delay in following up - I think getting that try block in place is working out well so far.  I can definitely see one runner for all accounts being much easier to maintain/support based on how atlantis uses pr's and is webhook driven.  On the other hand the blast radius gets fairly large, I guess with how iam is structured in aws generally most things end up being this way via delegates.
