### ISSUE TITLE
Problem installing with homebrew - sha mismatch

### ISSUE THREAD

**Issue by boris-gaber** [transcend-io/terragrunt-atlantis-config#93]
Exact same thing as https://github.com/transcend-io/terragrunt-atlantis-config/issues/83

`brew install transcend-io/tap/terragrunt-atlantis-config
==> Installing terragrunt-atlantis-config from transcend-io/tap
==> Downloading https://homebrew.transcend.io/terragrunt-atlantis-config/0.10.1/terragrunt-atlantis-config_0.1
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 88826204f7f2cda46bc27c8216d5b3210d061dd8d1d6cdb7ceca90af7bced6b6
  Actual: f93257f9ec4323bac26d34c367336583ba11096dabb3636bd50393f0ed16ac9c`

**Comment by dmattia** [comment]
Thanks for this. I think this issue is coming up again because I'm not enforcing that I bump the version between each PR, which is causing the S3 file homebrew points at to be overwritten with a file with a different SHA.

I can add that enforcement soon so this should hopefully stop coming up.

For now, I corrected the SHA, so the install command should work
